config/routes.rb
Rails.application.routes.draw do
  get 'crm/index'
  root 'landing#index'

  mount Sidekiq::Web => '/queues'
  mount ActionCable.server => '/cable'

  devise_for :accounts,
  controllers: {
    sessions: 'accounts/sessions'
  }

  get '/serviceworker.js' => 'serviceworkers#serviceworker'
  get '/manifest.json' => 'serviceworkers#manifest'
  get '/offline.html' => 'serviceworkers#offline'
  post '/push' => 'serviceworkers#push'

  resources :dashboard
  resources :crm
end

app/controllers/crm_controller.rb
class CrmController < ApplicationController
  before_action :authenticate_account!

  def index
    @customers = ListCustomer.run!
  end
end

app/helpers/crm_helper.rb
module CrmHelper
end

app/views/crm/_actions.html.slim
.row.mb-2
  .col-sm-2
    = link_to new_crm_path, class: 'btn btn-block btn-primary' do
      i.fas.fa-plus.mr-1
      = t('crm.new')
  .col-sm-10
    .float-sm-right
      = link_to new_crm_path, class: 'btn btn-inline-block btn-success mr-2' do
        i.far.fa-paper-plane.mr-1
        = t('crm.export')
      = link_to new_crm_path, class: 'btn btn-inline-block btn-secondary' do
        i.fas.fa-paperclip.mr-1
        = t('crm.import')

app/views/crm/_index-detail.html.slim
#crm-list

app/views/crm/index.html.slim
= content_for :active_crm_index, 'active'
= content_for :active_crm, 'active'

- add_breadcrumb( 'crm.list', crm_index_path)
.section-controller[data-controller='crm']
  .content-header
    .container-fluid
      = render partial: 'shared/breadcrumb', locals: { title: t('crm.index', {total: 0}).html_safe, target: 'crm.total' }
  .content-header
    .container-fluid
      = render 'crm/actions'
  section.content
    .container-fluid
      .row
        .col-sm-12
          = render 'crm/index-detail'