config/routes.rb
Rails.application.routes.draw do
  get 'crm/index'
  root 'landing#index'

  mount Sidekiq::Web => '/queues'
  mount ActionCable.server => '/cable'

  devise_for :accounts,
  controllers: {
    sessions: 'accounts/sessions'
  }

  get '/serviceworker.js' => 'serviceworkers#serviceworker'
  get '/manifest.json' => 'serviceworkers#manifest'
  get '/offline.html' => 'serviceworkers#offline'
  post '/push' => 'serviceworkers#push'

  resources :dashboard
  resources :crm
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  layout 'landing'
  
  def index
    @welcome = GetWelcome.run!
    
    respond_to do |format|
      format.html do |html|
        html.mobile
        html.tablet
      end
    end
  end
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/views/landing/_actions.html.slim
button.btn.btn-primary.float-right[data-action='click->landing#onClick']
  = t('authentication.next')

app/views/landing/_login.html.slim
= form_for resource, url: session_path(resource_name), html: { data: { action: 'submit->landing#onSubmit' }, autocomplete: 'off' } do |f|
  .input-group.mb-4
    i.fas.fa-user
    = f.text_field :login_by,
                    class: 'form-control',
                    placeholder: t('authentication.phone_email'),
                    name: 'login_by',
                    required: false,
                    'aria-label' => 'login_by',
                    autofocus: true,
                    autocapitalize: 'off',
                    autocomplete: 'off',
                    data: { target: 'landing.login_by' }

  .input-group.mb-4
    i.fas.fa-lock
    = f.password_field :password,
                        class: 'form-control',
                        name: 'password',
                        required: false,
                        placeholder: t('authentication.password'),
                        'aria-label' => 'Password',
                        autocomplete: 'off',
                        data: { target: 'landing.password' }

  button.btn.btn-gradient.btn-block.mb-5.d-none#button-submit[type='submit']
    = t('authentication.login')
                      

app/views/landing/_welcome.html.slim
h1= t('welcome', { time: t("times.#{welcome.day_time}") })
#typewriter
  .authentication-container-welcome-message
    = welcome.day_message[welcome.day_time]

app/views/landing/index.html+mobile.slim
= content_for :layout_template, 'landing.mobile'

#on-mobile
.ms-road[data-controller='landing']
  .authentication.animated.fadeIn.animation-delay-5
    .authentication-container
      .authentication-container--right
        .authentication-container-welcome
          = render partial: 'landing/welcome', locals: { welcome: @welcome }
        .authentication-container-login
          .form-authentication
            = render 'landing/login'
        .authentication-container-footer
          = render 'landing/actions'

app/views/landing/index.html.slim
= content_for :layout_template, 'landing'
.ms-road[data-controller='landing']
  .authentication.animated.fadeIn.animation-delay-5
    .authentication-container
      .authentication-container--left.float-left
        .authentication-container--logo
      .authentication-container--right.float-left
        .authentication-container-welcome
          = render partial: 'landing/welcome', locals: { welcome: @welcome }
        .authentication-container-login
          .form-authentication
            = render 'landing/login'
        .authentication-container-footer
          = render 'landing/actions'