config/routes.rb
Rails.application.routes.draw do
  get 'crm/index'
  root 'landing#index'

  mount Sidekiq::Web => '/queues'
  mount ActionCable.server => '/cable'

  devise_for :accounts,
  controllers: {
    sessions: 'accounts/sessions'
  }

  get '/serviceworker.js' => 'serviceworkers#serviceworker'
  get '/manifest.json' => 'serviceworkers#manifest'
  get '/offline.html' => 'serviceworkers#offline'
  post '/push' => 'serviceworkers#push'

  resources :dashboard
  resources :crm
end

app/views/layouts/partials/_comment.html.slim
a.nav-link[data-toggle='dropdown' href='javascript:void(0)']
  i.far.fa-comments
  span.badge.badge-danger.navbar-badge[data-target='comment.total']
.dropdown-menu.dropdown-menu-lg.dropdown-menu-right
  a.dropdown-item[href='javascript:void(0)']
    .media
      img.img-size-50.mr-3.img-circle[src=account_avatar alt='User Avatar']
      .media-body
        h3.dropdown-item-title
          |  Brad Diesel 
          span.float-right.text-sm.text-danger
            i.fas.fa-star
        p.text-sm
          | Call me whenever you can...
        p.text-sm.text-muted
          i.far.fa-clock.mr-1
          |  4 Hours Ago
  .dropdown-divider
  a.dropdown-item[href='#']
    .media
      img.img-size-50.img-circle.mr-3[src=account_avatar alt='User Avatar']
      .media-body
        h3.dropdown-item-title
          |  John Pierce 
          span.float-right.text-sm.text-muted
            i.fas.fa-star
        p.text-sm
          | I got your message bro
        p.text-sm.text-muted
          i.far.fa-clock.mr-1
          |  4 Hours Ago
  .dropdown-divider
  a.dropdown-item[href='#']
    .media
      img.img-size-50.img-circle.mr-3[src=account_avatar alt='User Avatar']
      .media-body
        h3.dropdown-item-title
          |  Nora Silvester 
          span.float-right.text-sm.text-warning
            i.fas.fa-star
        p.text-sm
          | The subject goes here
        p.text-sm.text-muted
          i.far.fa-clock.mr-1
          |  4 Hours Ago
  .dropdown-divider
  a.dropdown-item.dropdown-footer[href='#']
    | See All Messages

app/views/layouts/partials/_control-sidebar.html.slim
aside.control-sidebar.control-sidebar-dark
  .p-0
    = render 'shared/chat'
  .p-3

app/views/layouts/partials/_favicon.html.slim
= favicon_link_tag '/icons/apple-icon-57x57.png', sizes: '57x57', rel: 'apple-touch-icon', type: 'image/png'
= favicon_link_tag '/icons/apple-icon-60x60.png', sizes: '60x60', rel: 'apple-touch-icon', type: 'image/png'
= favicon_link_tag '/icons/apple-icon-72x72.png', sizes: '72x72', rel: 'apple-touch-icon', type: 'image/png'
= favicon_link_tag '/icons/apple-icon-76x76.png', sizes: '76x76', rel: 'apple-touch-icon', type: 'image/png'
= favicon_link_tag '/icons/apple-icon-114x114.png', sizes: '114x114', rel: 'apple-touch-icon', type: 'image/png'
= favicon_link_tag '/icons/apple-icon-120x120.png', sizes: '120x120', rel: 'apple-touch-icon', type: 'image/png'
= favicon_link_tag '/icons/apple-icon-144x144.png', sizes: '144x144', rel: 'apple-touch-icon', type: 'image/png'
= favicon_link_tag '/icons/apple-icon-152x152.png', sizes: '152x152', rel: 'apple-touch-icon', type: 'image/png'
= favicon_link_tag '/icons/apple-icon-180x180.png', sizes: '180x180', rel: 'apple-touch-icon', type: 'image/png'
= favicon_link_tag '/icons/android-icon-192x192.png', sizes: '192x192', rel: 'icon', type: 'image/png'
= favicon_link_tag '/favicon-32x32.png', sizes: '32x32', rel: 'icon', type: 'image/png'
= favicon_link_tag '/favicon-96x96.png', sizes: '96x96', rel: 'icon', type: 'image/png'
= favicon_link_tag '/favicon-16x16.png', sizes: '16x16', rel: 'icon', type: 'image/png'

link[rel='manifest preload' href='/manifest.json']

app/views/layouts/partials/_head.html.slim
meta[charset='utf-8']

title
 = meta_title

meta[name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no']
meta[name='description' content=meta_description]
meta[name='robots' content=meta_robots]
meta[name='msapplication-TileColor' content='#ffffff']
meta[name='msapplication-TileImage' content='/icons/ms-icon-144x144.png']
meta[name='apple-mobile-web-app-title' content='share-cv.xyz']
meta[name='apple-mobile-web-app-capable' content='yes']

/ Change the color of the browser bar
meta[name='theme-color' content='#ffffff']
meta[name='msapplication-navbutton-color' content='#ffffff']
meta[name='apple-mobile-web-app-status-bar-style' content='#ffffff']

link[rel='canonical' href=(canonical_url)]
link[rel='manifest preload' href='/manifest.json']
link[rel='stylesheet' href='https://fonts.googleapis.com/css?family=Roboto:400,400i,500,500i,700,700i,900,900i&display=swap']

= render 'layouts/partials/favicon'

= open_graph
= csrf_meta_tags
= csp_meta_tag

app/views/layouts/partials/_main-footer.html.slim
footer.main-footer
  strong
    = t('footer.copyright').html_safe
  .d-none.d-sm-inline-block
    = t('footer.reverved')

#resource[data-resource-id=current_account&.id]

app/views/layouts/partials/_main-header.html.slim
nav.main-header.navbar.navbar-expand.navbar-primary.navbar-dark
  = render 'layouts/partials/menu-items'
  / = render partial: 'layouts/partials/search', locals: { main_header: true }
  ul.navbar-nav.ml-auto
    li.nav-item.dropdown[data-controller='comment']
      #main-comment
        = render 'layouts/partials/comment'
    li.nav-item.dropdown[data-controller='notification']
      #main-notification
        = render 'layouts/partials/notification'
    li.nav-item.dropdown.user.user-menu
      = render 'layouts/partials/user-account'

    li.nav-item
      a.nav-link[data-widget='control-sidebar' data-slide='true' href='javascript:void(0)']
        i.fas.fa-th-large

app/views/layouts/partials/_menu-items.html.slim
ul.navbar-nav
  li.nav-item
    a.nav-link[data-widget='pushmenu' href='#']
      i.fas.fa-bars
  / li.nav-item.d-none.d-sm-inline-block
  /   a.nav-link[href='index3.html']
  /     | Home
  / li.nav-item.d-none.d-sm-inline-block
  /   a.nav-link[href='#']
  /     | Contact
  / li.nav-item.dropdown
  /   a#navbarDropdown.nav-link.dropdown-toggle[href='#' role='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false']
  /     |  Help 
  /   .dropdown-menu[aria-labelledby='navbarDropdown']
  /     a.dropdown-item[href='#']
  /       | FAQ
  /     a.dropdown-item[href='#']
  /       | Support
  /     .dropdown-divider
  /     a.dropdown-item[href='#']
  /       | Contact

app/views/layouts/partials/_notification.html.slim
a.nav-link[data-toggle='dropdown' href='javascript:void(0)']
  i.far.fa-bell
  span.badge.badge-warning.navbar-badge
    | 15
.dropdown-menu.dropdown-menu-lg.dropdown-menu-right
  span.dropdown-header
    | 15 Notifications
  .dropdown-divider
  a.dropdown-item[href='#']
    i.fas.fa-envelope.mr-2
    |  4 new messages 
    span.float-right.text-muted.text-sm
      | 3 mins
  .dropdown-divider
  a.dropdown-item[href='#']
    i.fas.fa-users.mr-2
    |  8 friend requests 
    span.float-right.text-muted.text-sm
      | 12 hours
  .dropdown-divider
  a.dropdown-item[href='#']
    i.fas.fa-file.mr-2
    |  3 new reports 
    span.float-right.text-muted.text-sm
      | 2 days
  .dropdown-divider
  a.dropdown-item.dropdown-footer[href='#']
    | See All Notifications

app/views/layouts/partials/_search.html.slim
- if !local_assigns[:main_header]
  / form.sidebar-form
  /   .input-group
  /     input.form-control.form-control-sidebar.box-shadow-none[type='search' placeholder='Search' aria-label='Search']
  /     .input-group-append
  /       button.btn.btn-sidebar[type='submit']
  /         i.fas.fa-search
- else
  form.form-inline.ml-3
    .input-group.input-group-sm
      input.form-control.form-control-navbar.box-shadow-none[type='search' placeholder='Search' aria-label='Search']
      .input-group-append
        button.btn.btn-navbar[type='submit']
          i.fas.fa-search

app/views/layouts/partials/_sidebar-items.html.slim
/ - @sidebar_items.each do |sidebar_item|
/   li.nav_item
/     a.nav-link[href=sidebar_item.url class=sidebar_item.active]
/       i.nav-icon.fas.fa-tachometer-alt
/       p
/         = sidebar_item.title
li.nav-item
  a.nav-link[href=dashboard_index_path class=yield(:active_dashboard)]
    i.nav-icon.fas.fa-tachometer-alt
    p
      = t('sidebar.dashboard.title')
li.nav-item.has-treeview.menu-close
  a.nav-link[href='javascript:void(0)' class=yield(:active_crm)]
    i.nav-icon.fas.fa-users
    p
      = t('sidebar.crm.title')
      i.right.fas.fa-angle-left
  ul.nav.nav-treeview
    li.nav-item
      a.nav-link[href=crm_index_path class=yield(:active_crm_index)]
        i.fas.fa-list-alt.nav-icon
        p
          = t('sidebar.crm.list')
    li.nav-item
      a.nav-link[href='./index.html']
        i.far.fa-circle.nav-icon
        p
          = t('sidebar.crm.care')
    li.nav-item
      a.nav-link[href='./index2.html']
        i.far.fa-circle.nav-icon
        p
          = t('sidebar.crm.config')

app/views/layouts/partials/_sidebar.html.slim
aside.main-sidebar.sidebar-dark-primary.elevation-4.sidebar-no-expand
  a.brand-link[href='javascript:void(0)']
    = image_tag 'demo-rails6/logos/manifest/logo-192x192.png', class: 'brand-image img-circle elevation-3'
    span.brand-text.font-weight-light
      = t('seo.default.website_name')
  .slimScrollDiv[style='position: relative; overflow: hidden; width: auto; height: 652px;']
    .sidebar[style='min-height: 652px; overflow: hidden; width: auto; height: 652px;']
      .user-panel.mt-3.pb-3.mb-3.d-flex
        .image
          = image_tag account_avatar, class: 'img-circle elevation-2', alt: 'Account Image'
        .info
          a.d-block.text-capitalize[href='#']
            = current_account_name
      
      = render 'layouts/partials/search'
      nav.mt-2
        ul.nav.nav-pills.nav-sidebar.flex-column.nav-compact[data-widget='treeview' role='menu' data-accordion='false' data-controller='link']
          = render 'layouts/partials/sidebar-items'

app/views/layouts/partials/_tag_link.html.slim
#modal-holder

app/views/layouts/partials/_user-account.html.slim
a.nav-link[data-toggle='dropdown' href='javascript:void(0)']
  = image_tag account_avatar, class: 'user-image user-circle-25', alt: 'Account Image'
  span.text-capitalize.d-none.d-sm-inline-block
    = current_account_name

.dropdown-menu.dropdown-menu-lg.dropdown-menu-right
  .card.card-widget.widget-user.mb-0
    .widget-user-header.bg-info
      h3.widget-user-username Card Tools
      h5.widget-user-desc CEO
    .widget-user-image
      = image_tag account_avatar, class: 'img-circle elevation-2', alt: 'Account Image'
    .card-footer
      .d-none.d-sm-block
        .row
          .col-sm-6
            a.btn.btn-secondary.btn-block[href='javascript:void(0)']
              = t('account.profile')
          .col-sm-6
            = link_to destroy_account_session_path, method: :delete, data: { 'confirm': t('confirm.signout') }, class: 'btn btn-secondary btn-block'  do
              = t('account.logout')
      .d-sm-none
        .row
          .col-4
            a.btn.btn-secondary.btn-block[href='javascript:void(0)']
              i.fas.fa-user
          .col-4
          .col-4
            = link_to destroy_account_session_path, method: :delete, data: { 'confirm': t('confirm.signout') }, class: 'btn btn-secondary btn-block'  do
              i.fas.fa-sign-out-alt